const form=document.querySelector('#formBusca');const input=document.querySelector('#cep');const mensagem=document.querySelector('#mensagem');const resultado=document.querySelector('#resultado');const chave='historicoBuscaCep';let enderecoAtual='';
input.addEventListener('input',()=>{let v=input.value.replace(/\D/g,'').slice(0,8);input.value=v.length>5?`${v.slice(0,5)}-${v.slice(5)}`:v});
form.addEventListener('submit',async e=>{e.preventDefault();const cep=input.value.replace(/\D/g,'');if(!/^\d{8}$/.test(cep)){mostrarMensagem('Digite um CEP válido com 8 números.',true);resultado.classList.remove('visivel');return}mostrarMensagem('Consultando...');try{const resposta=await fetch(`https://viacep.com.br/ws/${cep}/json/`);if(!resposta.ok)throw new Error('Falha na consulta');const dados=await resposta.json();if(dados.erro){mostrarMensagem('CEP não encontrado. Confira os números e tente novamente.',true);resultado.classList.remove('visivel');return}exibir(dados);salvarHistorico(dados);mostrarMensagem('Consulta concluída.')}catch{mostrarMensagem('Não foi possível consultar agora. Verifique sua conexão e tente novamente.',true);resultado.classList.remove('visivel')}});
function mostrarMensagem(texto,erro=false){mensagem.textContent=texto;mensagem.classList.toggle('erro',erro)}
function valor(v){return v&&v.trim()?v:'Não informado'}
function exibir(d){document.querySelector('#cepResultado').textContent=d.cep;document.querySelector('#logradouro').textContent=valor(d.logradouro);document.querySelector('#bairro').textContent=valor(d.bairro);document.querySelector('#cidade').textContent=valor(d.localidade);document.querySelector('#estado').textContent=d.estado?`${d.estado} (${d.uf})`:valor(d.uf);document.querySelector('#ddd').textContent=valor(d.ddd);document.querySelector('#ibge').textContent=valor(d.ibge);enderecoAtual=[d.logradouro,d.bairro,d.localidade,d.uf,d.cep].filter(Boolean).join(', ');resultado.classList.add('visivel')}
function lerHistorico(){return JSON.parse(localStorage.getItem(chave)||'[]')}
function salvarHistorico(d){let itens=lerHistorico().filter(i=>i.cep!==d.cep);itens.unshift({cep:d.cep,logradouro:d.logradouro,bairro:d.bairro,localidade:d.localidade,uf:d.uf,estado:d.estado,ddd:d.ddd,ibge:d.ibge});localStorage.setItem(chave,JSON.stringify(itens.slice(0,6)));renderizarHistorico()}
function renderizarHistorico(){const itens=lerHistorico();const area=document.querySelector('#historico');area.innerHTML='';document.querySelector('#historicoVazio').style.display=itens.length?'none':'block';itens.forEach(item=>{const div=document.createElement('div');div.className='item-historico';const texto=document.createElement('div');const titulo=document.createElement('strong');titulo.textContent=item.cep;const detalhe=document.createElement('span');detalhe.textContent=`${item.localidade} - ${item.uf}${item.logradouro?' · '+item.logradouro:''}`;texto.append(titulo,detalhe);const seta=document.createElement('span');seta.textContent='Ver novamente →';div.append(texto,seta);div.addEventListener('click',()=>{exibir(item);input.value=item.cep;mostrarMensagem('Endereço carregado do histórico.');resultado.scrollIntoView({behavior:'smooth',block:'nearest'})});area.appendChild(div)})}
document.querySelector('#copiar').addEventListener('click',async()=>{if(!enderecoAtual)return;try{await navigator.clipboard.writeText(enderecoAtual);const b=document.querySelector('#copiar');b.textContent='Copiado';setTimeout(()=>b.textContent='Copiar endereço',1200)}catch{mostrarMensagem('Não foi possível copiar automaticamente.',true)}});
document.querySelector('#limparHistorico').addEventListener('click',()=>{localStorage.removeItem(chave);renderizarHistorico()});document.querySelector('#tema').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('temaBuscaCep',document.body.classList.contains('dark')?'dark':'light')});if(localStorage.getItem('temaBuscaCep')==='dark')document.body.classList.add('dark');renderizarHistorico();
